{% set name = "anymap-ts" %}
{% set version = "0.13.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/55/82/174654233c683cd3d075dde2063a02e2d6c9b2411fcbf7cf3704ac955950/anymap_ts-{{ version }}.tar.gz
  sha256: 82a0bcc6c79bba27fe9ed33c369da745ebd6ebc62156ff0d60d9d24ad07e6c1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder >=0.9.1
    - nodejs >=18
    - pip
  run:
    - python >={{ python_min }}
    - anywidget >=0.9.0
    - traitlets >=5.0.0
    - xyzservices >=2023.10.0

test:
  imports:
    - anymap_ts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/anymap-ts
  summary: A Python package for creating interactive maps with anywidget and TypeScript
  description: |
    anymap-ts is a Python package for creating interactive maps with anywidget and TypeScript.
  license: MIT
  license_file: LICENSE
  doc_url: https://ts.anymap.dev
  dev_url: https://github.com/opengeos/anymap-ts

extra:
  recipe-maintainers:
    - giswqs
