{% set name = "anymap-ts" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/c9/c1/e92dcd92e853a688e2f6ca830c7d8e4ec6bacedf0d02985de263eedf7a50/anymap_ts-{{ version }}.tar.gz
  sha256: 9e6c466b229f6158b34be920d29ad28a0251814344aee6acd1b80b7ab8ac4cf8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder >=0.9.1
    - nodejs >=18
    - pip
  run:
    - python >={{ python_min }}
    - anywidget >=0.9.0
    - traitlets >=5.0.0
    - xyzservices >=2023.10.0

test:
  imports:
    - anymap_ts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/anymap-ts
  summary: A Python package for creating interactive maps with anywidget and TypeScript
  description: |
    anymap-ts is a Python package for creating interactive maps with anywidget and TypeScript.
  license: MIT
  license_file: LICENSE
  doc_url: https://ts.anymap.dev
  dev_url: https://github.com/opengeos/anymap-ts

extra:
  recipe-maintainers:
    - giswqs
