{% set name = "anymap-ts" %}
{% set version = "0.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/96/0b/55e81d7372ee3be5c3c1deba7d898dfa9e82b84103dd07120b68729b955c/anymap_ts-{{ version }}.tar.gz
  sha256: ad308cf80c5b23a891bc9efb985157e73cc0ad26fd6002ad666e8b3d817be111

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder >=0.9.1
    - nodejs >=18
    - pip
  run:
    - python >={{ python_min }}
    - anywidget >=0.9.0
    - traitlets >=5.0.0
    - xyzservices >=2023.10.0

test:
  imports:
    - anymap_ts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/anymap-ts
  summary: A Python package for creating interactive maps with anywidget and TypeScript
  description: |
    anymap-ts is a Python package for creating interactive maps with anywidget and TypeScript.
  license: MIT
  license_file: LICENSE
  doc_url: https://ts.anymap.dev
  dev_url: https://github.com/opengeos/anymap-ts

extra:
  recipe-maintainers:
    - giswqs
