{% set name = "anymap-ts" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/2f/0c/505f58f1f212874e84393b9c87d96f7c7a134618aa18e01ac7cc6639cce6/anymap_ts-{{ version }}.tar.gz
  sha256: d47e75db96bb675d2a81fc054674bbef33e9effaca8f238184da89f44192d784

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder >=0.9.1
    - nodejs >=18
    - pip
  run:
    - python >={{ python_min }}
    - anywidget >=0.9.0
    - traitlets >=5.0.0
    - xyzservices >=2023.10.0

test:
  imports:
    - anymap_ts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/anymap-ts
  summary: A Python package for creating interactive maps with anywidget and TypeScript
  description: |
    anymap-ts is a Python package for creating interactive maps with anywidget and TypeScript.
  license: MIT
  license_file: LICENSE
  doc_url: https://ts.anymap.dev
  dev_url: https://github.com/opengeos/anymap-ts

extra:
  recipe-maintainers:
    - giswqs
