{% set name = "anymap-ts" %}
{% set version = "0.13.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/a4/36/667f5a8e37ef38538d7ec67b3c6ab66abb4960864a19dd695aafa4e42a15/anymap_ts-{{ version }}.tar.gz
  sha256: 0d6cf540dbe6ad927ff0ee4dd2983d5699feb6dfed85955a75b58b9a6f589972

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-jupyter-builder >=0.9.1
    - nodejs >=18
    - pip
  run:
    - python >={{ python_min }}
    - anywidget >=0.9.0
    - traitlets >=5.0.0
    - xyzservices >=2023.10.0

test:
  imports:
    - anymap_ts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opengeos/anymap-ts
  summary: A Python package for creating interactive maps with anywidget and TypeScript
  description: |
    anymap-ts is a Python package for creating interactive maps with anywidget and TypeScript.
  license: MIT
  license_file: LICENSE
  doc_url: https://ts.anymap.dev
  dev_url: https://github.com/opengeos/anymap-ts

extra:
  recipe-maintainers:
    - giswqs
